(ns grease.scrape.run
  "CLI entry point for scraping Apple docs and generating EDN spec files.

  Usage (from project root):
    clj -M -m grease.scrape.run CoreLocation
    clj -M -m grease.scrape.run Foundation CoreLocation AVFoundation UIKit CoreBluetooth

  For each framework named on the command line:
  1. Fetches the Apple developer docs JSON (cached to .cache/apple-docs/)
  2. Normalises to a grease EDN spec map via [[grease.scrape.normalize/framework->edn]]
  3. Validates the map via [[grease.ios.spec/validate]]
  4. Writes the EDN to resources/grease/api-specs/<Framework>.edn
  5. Updates resources/grease/api-specs/manifest.edn to include the new path

  Exit code 0 on success, 1 if any framework fails.

  Notes:
  - Existing EDN files are overwritten — never hand-edit scraper output.
  - Protocols and enums are not auto-scraped in normalizer v1; add them manually
    after running the scraper.
  - The `:framework` key in the output is (str/capitalize framework-name);
    ensure you pass the canonical Apple-casing (e.g. \"CoreLocation\" not \"corelocation\")."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [grease.ios.spec :as spec]
            [grease.scrape.normalize :as normalize]))

;; =============================================================================
;; Output paths
;; =============================================================================

(def ^:dynamic specs-dir
  "Root directory for EDN output. Bind in tests to a temp directory."
  "resources/grease/api-specs")

(def ^:dynamic manifest-path
  "Path to manifest.edn. Bind in tests to a temp directory.
  Defaults to specs-dir/manifest.edn — must be rebound independently
  when specs-dir is rebound, since this captures the default at load time."
  "resources/grease/api-specs/manifest.edn")

(defn edn-path
  "Returns the resources-relative classpath path for framework-name.
  e.g. \"CoreLocation\" -> \"grease/api-specs/CoreLocation.edn\""
  [framework-name]
  (str "grease/api-specs/" framework-name ".edn"))

(defn- edn-file
  "Returns the java.io.File for the output EDN, relative to project root."
  [framework-name]
  (io/file specs-dir (str framework-name ".edn")))

;; =============================================================================
;; Manifest management
;; =============================================================================

(defn- read-manifest
  "Reads the current manifest.edn. Returns {:specs [...]} or a default."
  []
  (let [f (io/file manifest-path)]
    (if (.exists f)
      (edn/read-string (slurp f))
      {:specs []})))

(defn- write-manifest!
  "Writes manifest map to manifest.edn with a comment header."
  [manifest]
  (let [f (io/file manifest-path)]
    (spit f
          (str ";; Manifest of all EDN framework specs in resources/grease/api-specs/.\n"
               ";; io/resource cannot enumerate a directory from a JAR, so this file\n"
               ";; is the authoritative list.  The scraper updates it automatically.\n\n"
               (with-out-str (pprint/pprint manifest))))))

(defn- ensure-in-manifest!
  "Adds edn-path-str to manifest :specs if not already present."
  [edn-path-str]
  (let [m    (read-manifest)
        specs (vec (:specs m))]
    (when-not (some #(= edn-path-str %) specs)
      (write-manifest! (assoc m :specs (conj specs edn-path-str))))))

;; =============================================================================
;; Per-framework scrape
;; =============================================================================

(defn scrape-framework!
  "Scrapes Apple docs for framework-name, validates, and writes EDN to disk.
  Returns the validated EDN spec map on success, or throws on failure.

  framework-name: canonical Apple-casing, e.g. \"CoreLocation\""
  [framework-name]
  (println (str "Scraping " framework-name "..."))
  (let [raw-edn  (normalize/framework->edn framework-name)
        ;; Override :framework to use the caller-supplied casing
        edn      (assoc raw-edn :framework framework-name)
        _        (spec/validate edn)
        out-file (edn-file framework-name)]
    (io/make-parents out-file)
    (spit out-file
          (str ";; " framework-name " framework spec — generated by grease.scrape.run.\n"
               ";; Run `clj -M -m grease.scrape.run " framework-name "` to regenerate.\n"
               ";; Add protocols/enums manually — not auto-scraped in normalizer v1.\n\n"
               (with-out-str (pprint/pprint edn))))
    (ensure-in-manifest! (edn-path framework-name))
    (println (str "  -> " (.getPath out-file)
                  " (" (count (:classes edn)) " classes)"))
    edn))

;; =============================================================================
;; Entry point
;; =============================================================================

(defn -main
  "CLI entry point.  Accepts one or more framework names as arguments."
  [& args]
  (when (empty? args)
    (println "Usage: clj -M -m grease.scrape.run <Framework> [Framework ...]")
    (println "Example: clj -M -m grease.scrape.run CoreLocation AVFoundation")
    (System/exit 1))
  (let [failures (atom [])]
    (doseq [fw args]
      (try
        (scrape-framework! fw)
        (catch Exception e
          (println (str "ERROR scraping " fw ": " (.getMessage e)))
          (swap! failures conj fw))))
    (if (seq @failures)
      (do (println (str "Failed frameworks: " (str/join ", " @failures)))
          (System/exit 1))
      (println "Done."))))
